fix: config health check endpoints for project

diff --git a/.github/workflows/main_be-container-explorenow.yml b/.github/workflows/main_be-container-explorenow.yml
--- a/.github/workflows/main_be-container-explorenow.yml
+++ b/.github/workflows/main_be-container-explorenow.yml
@@ -49,6 +49,17 @@ jobs:
         slot-name: 'production'
         publish-profile: ${{ secrets.AzureAppService_PublishProfile_521dd4021dc64635b6a6fb91be24c22d }}
         images: 'myexplorenow.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_283cb2cdd354458895117cc70b5b693e }}/be:${{ github.sha }}'
+    
+     - name: Health check
+      run: |
+        sleep 30  # Wait for the app to start
+        response=$(curl -sS -o /dev/null -w "%{http_code}" https://be-container-explorenow-duhthwhkecf0eef7.southeastasia-01.azurewebsites.net/health)
+        if [ $response = "200" ]; then
+          echo "Health check passed"
+        else
+          echo "Health check failed with status code $response"
+          exit 1
+        fi
         
     - name: Verify deployment
       run: |
